version: "3.9"

# Define our services (containers)
services:
  # Our main service: the Azure DevOps agent with SSH
  azdo-agent:
    # Build configuration
    build:
      context: .              # Build from current directory
      dockerfile: Dockerfile  # Using this Dockerfile
    
    # Container name (easier to reference)
    container_name: azdo-agent
    
    # Restart policy: restart unless explicitly stopped
    restart: unless-stopped
    
    # Environment variables (from .env file)
    environment:
      # Azure DevOps configuration
      AZP_URL: "${AZP_URL}"
      AZP_TOKEN: "${AZP_TOKEN}"
      AZP_POOL: "${AZP_POOL}"
      AZP_AGENT_NAME: "${AZP_AGENT_NAME}"
      AZP_WORK_DIR: "${AZP_WORK_DIR}"
      
      # SSH configuration
      SSH_PASSWORD: "${SSH_PASSWORD}"
      # Uncomment these if you want key-based SSH:
      # SSH_PUBLIC_KEY: "${SSH_PUBLIC_KEY}"
      # SSH_DISABLE_PASSWORD: "${SSH_DISABLE_PASSWORD}"
    
    # Port mapping: host:container
    # SSH on port 2222 (host) → port 22 (container)
    # Bound to 127.0.0.1 (localhost only) for security
    ports:
      - "127.0.0.1:2222:22"
    
    # Persistent volumes (survive container restarts)
    volumes:
      # Agent work directory (source code, build artifacts)
      - ./_agent_work:/azp/agent/_work
      
      # Agent logs (diagnostic information)
      - ./_agent_logs:/azp/agent/_diag