site_name: Workshop Utils Docs
site_description: Documentation for utility helpers (filesystem & time) used in workshop_builder.
site_author: Your Team
repo_url: https://example.com/your-repo
theme:
  name: mkdocs
nav:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - Guides:
      - Safe Filenames: guides/safe-filenames.md
      - Atomic Writes: guides/atomic-writes.md
      - Temporary Directories: guides/temp-dirs.md
      - Durations & Time: guides/durations.md
  - API Reference:
      - utils.fs: api/fs.md
      - utils.time: api/time.md
  - Recipes: recipes.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Security: security.md
  - Configuration: configuration.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://example.com/your-repo
