name: 'Azure-2-$(Date:yyyyMMdd)$(Rev:.r)'
trigger:
  branches: { include: [ main, develop, 'feature/*' ] }
  paths:    { include: [ 'Folder3/**' ], exclude: [ '**/*.md' ] }
pool: { vmImage: 'ubuntu-latest' }
steps:
- checkout: self
  fetchDepth: 1
- script: echo "Azure-2 build triggered by Folder3 changes"
